apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ehjnlqeim-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ehjnlqeim-dotnet-basic-gitops